// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/dict.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListChildrenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListChildrenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListChildrenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListChildrenRequestMultiError, or nil if none found.
func (m *ListChildrenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListChildrenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := ListChildrenRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListChildrenRequestMultiError(errors)
	}

	return nil
}

// ListChildrenRequestMultiError is an error wrapping multiple validation
// errors returned by ListChildrenRequest.ValidateAll() if the designated
// constraints aren't met.
type ListChildrenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListChildrenRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListChildrenRequestMultiError) AllErrors() []error { return m }

// ListChildrenRequestValidationError is the validation error returned by
// ListChildrenRequest.Validate if the designated constraints aren't met.
type ListChildrenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListChildrenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListChildrenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListChildrenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListChildrenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListChildrenRequestValidationError) ErrorName() string {
	return "ListChildrenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListChildrenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListChildrenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListChildrenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListChildrenRequestValidationError{}

// Validate checks the field values on ListChildrenReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListChildrenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListChildrenReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListChildrenReplyMultiError, or nil if none found.
func (m *ListChildrenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListChildrenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListChildrenReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListChildrenReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListChildrenReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListChildrenReplyMultiError(errors)
	}

	return nil
}

// ListChildrenReplyMultiError is an error wrapping multiple validation errors
// returned by ListChildrenReply.ValidateAll() if the designated constraints
// aren't met.
type ListChildrenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListChildrenReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListChildrenReplyMultiError) AllErrors() []error { return m }

// ListChildrenReplyValidationError is the validation error returned by
// ListChildrenReply.Validate if the designated constraints aren't met.
type ListChildrenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListChildrenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListChildrenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListChildrenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListChildrenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListChildrenReplyValidationError) ErrorName() string {
	return "ListChildrenReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListChildrenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListChildrenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListChildrenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListChildrenReplyValidationError{}

// Validate checks the field values on ListChildrenReply_Dict with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListChildrenReply_Dict) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListChildrenReply_Dict with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListChildrenReply_DictMultiError, or nil if none found.
func (m *ListChildrenReply_Dict) ValidateAll() error {
	return m.validate(true)
}

func (m *ListChildrenReply_Dict) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListChildrenReply_DictValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListChildrenReply_DictValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListChildrenReply_DictValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListChildrenReply_DictValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListChildrenReply_DictValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListChildrenReply_DictValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Value

	// no validation rules for DictCode

	// no validation rules for HasChildren

	if len(errors) > 0 {
		return ListChildrenReply_DictMultiError(errors)
	}

	return nil
}

// ListChildrenReply_DictMultiError is an error wrapping multiple validation
// errors returned by ListChildrenReply_Dict.ValidateAll() if the designated
// constraints aren't met.
type ListChildrenReply_DictMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListChildrenReply_DictMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListChildrenReply_DictMultiError) AllErrors() []error { return m }

// ListChildrenReply_DictValidationError is the validation error returned by
// ListChildrenReply_Dict.Validate if the designated constraints aren't met.
type ListChildrenReply_DictValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListChildrenReply_DictValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListChildrenReply_DictValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListChildrenReply_DictValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListChildrenReply_DictValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListChildrenReply_DictValidationError) ErrorName() string {
	return "ListChildrenReply_DictValidationError"
}

// Error satisfies the builtin error interface
func (e ListChildrenReply_DictValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListChildrenReply_Dict.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListChildrenReply_DictValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListChildrenReply_DictValidationError{}
