// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/yrcs/yuneto/app/datadict/internal/biz"
	"github.com/yrcs/yuneto/app/datadict/internal/conf"
	"github.com/yrcs/yuneto/app/datadict/internal/data"
	"github.com/yrcs/yuneto/app/datadict/internal/server"
	"github.com/yrcs/yuneto/app/datadict/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	dictRepo := data.NewDictRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	dictUsecase := biz.NewDictUsecase(dictRepo, transaction, logger)
	dataDictService := service.NewDataDictService(dictUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, dataDictService, logger)
	httpServer := server.NewHTTPServer(confServer, dataDictService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
