definitions:
  anypb.Any:
    properties:
      type_url:
        description: |-
          A URL/resource name that uniquely identifies the type of the serialized
          protocol buffer message. This string must contain at least
          one "/" character. The last segment of the URL's path must represent
          the fully qualified name of the type (as in
          `path/google.protobuf.Duration`). The name should be in a canonical form
          (e.g., leading "." is not accepted).

          In practice, teams usually precompile into the binary all types that they
          expect it to use in the context of Any. However, for URLs which use the
          scheme `http`, `https`, or no scheme, one can optionally set up a type
          server that maps type URLs to message definitions as follows:

          * If no scheme is provided, `https` is assumed.
          * An HTTP GET on the URL must yield a [google.protobuf.Type][]
            value in binary format, or produce an error.
          * Applications are allowed to cache lookup results based on the
            URL, or have them precompiled into a binary to avoid any
            lookup. Therefore, binary compatibility needs to be preserved
            on changes to types. (Use versioned type names to manage
            breaking changes.)

          Note: this functionality is not currently available in the official
          protobuf release, and it is not used for type URLs beginning with
          type.googleapis.com.

          Schemes other than `http`, `https` (or the empty scheme) might be
          used with implementation specific semantics.
        type: string
      value:
        description: Must be a valid serialized protocol buffer of the above specified
          type.
        items:
          type: integer
        type: array
    type: object
  pagination.PagingReply:
    properties:
      items:
        items:
          $ref: '#/definitions/anypb.Any'
        type: array
      total:
        type: integer
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. Negative
          second values with fractions must still have non-negative nanos values
          that count forward in time. Must be from 0 to 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch
          1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
          9999-12-31T23:59:59Z inclusive.
        type: integer
    type: object
  v1.AddHospitalSettingRequest:
    properties:
      apiUrl:
        type: string
      contactMobile:
        type: string
      contactPerson:
        type: string
      locked:
        type: integer
      name:
        type: string
      registrationNumber:
        type: string
      signatureKey:
        type: string
    type: object
  v1.CommonAddReply:
    properties:
      createdAt:
        $ref: '#/definitions/timestamppb.Timestamp'
      id:
        type: integer
      updatedAt:
        $ref: '#/definitions/timestamppb.Timestamp'
    type: object
  v1.CommonEditReply:
    properties:
      id:
        type: integer
      updatedAt:
        $ref: '#/definitions/timestamppb.Timestamp'
    type: object
  v1.DeleteHospitalSettingsRequest:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  v1.EditHospitalSettingRequest:
    properties:
      apiUrl:
        type: string
      contactMobile:
        type: string
      contactPerson:
        type: string
      id:
        type: integer
      locked:
        type: integer
      name:
        type: string
      registrationNumber:
        type: string
      signatureKey:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: 本文档描述了后台管理系统微服务接口定义。
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: YunETO (云医通) 后台管理系统 API
  version: "1.0"
paths:
  /admin/hospital/hospitalSettings:
    delete:
      consumes:
      - application/json
      description: 接收 json 以批量删除医院设置
      parameters:
      - description: 医院设置 id 数组
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/v1.DeleteHospitalSettingsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 批量删除设置
      tags:
      - 批量删除医院设置
    get:
      consumes:
      - application/json
      description: 医院设置分页列表
      parameters:
      - description: 页码
        format: uint32
        in: query
        name: page
        type: integer
      - description: 每页条目数
        format: uint32
        in: query
        name: pageSize
        type: integer
      - description: 查询参数
        in: query
        name: query[name]
        type: string
      - description: 排序参数
        enum:
        - 0
        - 1
        - 2
        in: query
        name: orderBy[name]
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pagination.PagingReply'
      summary: 医院设置列表
      tags:
      - 获取医院设置列表
    post:
      consumes:
      - application/json
      description: 接收 json 以添加医院设置
      parameters:
      - description: 医院设置属性
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/v1.AddHospitalSettingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CommonAddReply'
      summary: 添加设置
      tags:
      - 添加医院设置
  /admin/hospital/hospitalSettings/{id}:
    delete:
      consumes:
      - application/json
      description: 接收 id 以删除医院设置
      parameters:
      - description: 医院设置 id
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 删除设置
      tags:
      - 删除医院设置
    put:
      consumes:
      - application/json
      description: 接收 id 与 json 以编辑医院设置
      parameters:
      - description: 医院设置 id
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: 医院设置属性
        in: body
        name: message
        schema:
          $ref: '#/definitions/v1.EditHospitalSettingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CommonEditReply'
      summary: 编辑设置
      tags:
      - 编辑医院设置
  /admin/hospital/hospitalSettings/{id}/{locked}:
    put:
      consumes:
      - application/json
      description: 接收 id 与 locked 以锁定/解锁医院设置
      parameters:
      - description: 锁定/解锁医院设置
        format: uint64
        in: path
        name: id
        required: true
        type: integer
      - description: 锁定/解锁状态
        enum:
        - 0
        - 1
        in: path
        name: locked
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CommonEditReply'
      summary: 锁定/解锁设置
      tags:
      - 锁定/解锁医院设置
swagger: "2.0"
